- name: Wipe web app
  when: web_app_full_wipe
  block:
    - name: Remove web app
      docker_container:
        name: "{{ web_app_container_name }}"
        state: absent
        keep_volumes: false
      tags: 
        - wipe